channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.10.14
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - cloudpickle==3.0.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - exceptiongroup==1.2.1
      - farama-notifications==0.0.4
      - filelock==3.13.4
      - fonttools==4.51.0
      - fsspec==2024.3.1
      - gymnasium==0.28.1
      - iniconfig==2.0.0
      - jax-jumpy==1.0.0
      - jinja2==3.1.3
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - packaging==24.0
      - pandas==2.2.2
      - pillow==10.3.0
      - pluggy==1.5.0
      - pybullet==3.2.6
      - pyparsing==3.1.2
      - pytest==7.4.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - scipy==1.13.0
      - six==1.16.0
      - stable-baselines3==2.3.0
      - sympy==1.12
      - tomli==2.0.1
      - torch==2.2.2
      - transforms3d==0.4.1
      - triton==2.2.0
      - typing-extensions==4.11.0
      - tzdata==2024.1
